### ISSUE TITLE
Poll for multiple gpio edges

### ISSUE THREAD

**Issue by mark-blackburn-etcorp** [vsergeev/python-periphery#21]
A static method to poll multiple GPIO objects for edges. Something like this:

    @staticmethod
    def poll_multiple(gpios, timeout):
        # Setup epoll
        p = select.epoll()
        for gpio in gpios:
            p.register(gpio._fd, select.EPOLLIN | select.EPOLLET | select.EPOLLPRI)

        p.poll(0)
        events = p.poll(timeout)
        print("events = %s" % repr(events))
        result = []
        gpio_fds_triggered = zip(*events)[0]
        for gpio in gpios:
            result.append(gpio._fd in gpio_fds_triggered)
        return result

**Comment by vsergeev** [comment]
This would be great to have. I'll have to revisit this after the upcoming v2.0.0 release with character device GPIOs.
