### ISSUE TITLE
LICENSE file is missing in the tarball available from PyPi

### ISSUE THREAD

**Issue by texierp** [vsergeev/python-periphery#27]
Hi @vsergeev,

Would it be possible to put the license file in the archive 
available on PyPi ?

You can read the initial discussion on Buildroot's ML [1]

Thanks !

/Pierre-Jean 

[1] - http://lists.busybox.net/pipermail/buildroot/2019-June/253049.html

**Comment by vsergeev** [comment]
Sure, I will add it shortly.

**Comment by texierp** [comment]
Thanks :)

**Comment by vsergeev** [comment]
Fixed in v1.1.2. LICENSE file is now in all packages on https://pypi.org/project/python-periphery/#files.
