### ISSUE TITLE
Data from consecutive packets are merged  in serial module

### ISSUE THREAD

**Issue by xrombik** [vsergeev/python-periphery#30]
Serial module. Data from consecutive packets are merged until the number of bytes specified in read is reached, or timeout is reached. This is wrong behavior, because when using native open/read/write system calls data is not messed up from consecutive packets. With this PR problem is solved: https://github.com/vsergeev/python-periphery/pull/28

**Comment by vsergeev** [comment]
Resolved by 0f97423.
