### ISSUE TITLE
Any plans to create a configurable cs_change in spi.py?

### ISSUE THREAD

**Issue by Livius90** [vsergeev/python-periphery#37]
Hi!
It would be nice if there be any function or method to configurate spi_xfer.cs_change to 0 or 1.
My embedded board is supporting burst transfer in SPI and i need to create spi_xfer.cs_change=1 manually in transfer-function source always to use the normal mode.

**Comment by vsergeev** [comment]
Closing for now, see vsergeev/c-periphery#19.
