### ISSUE TITLE
RE: More of a Thank You...

### ISSUE THREAD

**Issue by silver2row** [vsergeev/python-periphery#45]
Hello,

First off, thank you for making this library. I have been able to use it w/ the BBAI from beagleboard.org. 

...

Secondly, do not ever quit. B/c of you and this lib, I have been able to perform some basic .py file structures to light a LED on and off with PWM. Next, fading!

Seth

P.S. If you need to close the "issue," do so but remember I am thankful. I cannot wait to try out the rest of your ideas on the AI.

**Comment by vsergeev** [comment]
Thanks Seth!
