### ISSUE TITLE
Example for using poll?

### ISSUE THREAD

**Issue by 9600** [vsergeev/python-periphery#5]
Do you have an example of using GPIO with poll? I'm trying to use this on an Intel Edison, have set edge to falling and no matter what parameter I pass to poll it always immediately returns with True, despite the state of the pin in question not having changed.

I can otherwise read and set pin states fine.

**Comment by vsergeev** [comment]
There's a few examples of poll in the hardware tests here: https://github.com/vsergeev/python-periphery/blob/v1.0.0/tests/test_gpio.py#L100

Does a read followed by poll work?

**Comment by jakogut** [comment]
@9600: I experienced the same issue, and I made a pull request to fix it.

**Comment by vsergeev** [comment]
@jakogut thanks! I'll be updating python-periphery this week with the pending PRs and a new release.

**Comment by jakogut** [comment]
@vsergeev Very cool, I'm glad to hear that such a useful library is still being maintained.
